# Functions 

Functions are a block of code that only run when called upon, and return a result after receiving information (arguments).


Components of the Function: 

def: Keyword used to define a function.
    
Add(x, y): ‘Add’ is the name of the function.
    Careful while defining the function: the name will be used to recall the function.

    (x, y): Parameters used to define the variable in the function operation.
    
    Arguments will be inserted in place of ‘x’ and ‘y’ as the values the respective     variable must take. 
        x = 5, y = 6 in the example.
        
return: keyword defined to return the desired outcome of the function.

In [1]:
def Add(x, y):
    result = x + y  #operation that the function is designed to conduct. 
    return result #indentations are important.

print(Add(5, 6))

11


Benefits of using Functions: Efficiency

Blocks of code that can be used anywhere by just calling them: One line of code, instead of repeating n lines that are present in the function.

Editing code is less time consuming: Only need to edit the code present in the function.

Functions are easy to maintain, deliver, transport and document. 

Function with Multiple Outputs

In [2]:
def func(x, y):
    Add = x + y
    Product = x*y
    Diff = x - y
    return Add, Product, Diff

Result = func(10, 5) #results of Add, Product, Diff are stored in a tuple (same order are listed in the function).
Add, Product, Diff = Result[0], Result[1], Result[2] #Saving Results within Variables. 

print(Add, Product, Diff)


15 50 5


For Loop within Function

Benefit: No need to keep recreating a new zeros matrix. 

The dimensions of the matrix are easily mutable, only need to execute one line of code, if x and y change. 

In [3]:
def Func_Matrix(x,y):  #Function inputs: x = no. of rows, and y = no. of columns
    import numpy as np #Each time the function is called, numpy gets imported
    Matrix = np.zeros([x, y]) #Each time the function is called, a zeros matrix of x and y dimension is created. 
    Size = Matrix.shape
    for i in range(Size[0]):
        for j in range(Size[1]):
            Matrix[i,j] = i*j
    return Matrix

Matrix = Func_Matrix(10, 10) 
print(Matrix)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]
 [ 0.  3.  6.  9. 12. 15. 18. 21. 24. 27.]
 [ 0.  4.  8. 12. 16. 20. 24. 28. 32. 36.]
 [ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45.]
 [ 0.  6. 12. 18. 24. 30. 36. 42. 48. 54.]
 [ 0.  7. 14. 21. 28. 35. 42. 49. 56. 63.]
 [ 0.  8. 16. 24. 32. 40. 48. 56. 64. 72.]
 [ 0.  9. 18. 27. 36. 45. 54. 63. 72. 81.]]


Running Function within a For Loop  

In [4]:
def Func(x):
    y = x**2
    add = x + y
    prod = x * y
    return add, prod

Add = []
Product = []
for x in range(10):
    result = Func(x)
    Add.append(result[0])
    Product.append(result[1])

print(f'Add: {Add}, Product: {Product}')

#Even faster way to iterate through a range of function input values and collect outputs. 

Add: [0, 2, 6, 12, 20, 30, 42, 56, 72, 90], Product: [0, 1, 8, 27, 64, 125, 216, 343, 512, 729]


Running a Function with conditons

In [5]:
def oddeven(x):
    if x%2 == 0:
        output = 'Input is even'
    else: 
        output = 'Input is odd'
    return print(output) #will directly print output

print(oddeven(15))

Input is odd
None


Fibonacci Sequence: Function, combining while loops and if-statements. 

Sequence in which each number is the sum of the two preceding ones.

    x represent the index of the sequence

https://www.mathsisfun.com/numbers/fibonacci-sequence.html

In [6]:
def Fibonacci(x):
    
    if x < 0: 
        output = 'Invalid Input'
    elif (x == 0) or (x == 1):
        output = x
    else: 
        a = 0 #index = x - 2
        b = 1 #index = x - 1
        i = 1 #i is at 1, so that the loop begins from x = 1, such that when x = 2, a = 0, b = 1, c = 1. 
        while i < x:
            c = a + b    #for x > 1: a = 0 and b = 1, c = a + b
            a = b   #for the next iteration, a = b = 1, and b = c = 1, then c = a+b = 1 + 1 = 2
            b = c
            i += 1
        output = c #output c from the final iteration (index = x)
    return output 

Fibonacci_Sequence = Fibonacci(6) #x = 6, which is the 7th value in the sequence. 
print(Fibonacci_Sequence)

8


## Calling Functions from another Script.

    Make Sure the script is saved in the same directory as the current script. 
    
    Script: Session_Functions.py
    
    Saved all the functions above in Session_Functions.py (without notes and output).
  

In [7]:

import Session_Functions as myfunc  #Congratulations, you have imported your own script package!

In [8]:
Add_Func = myfunc.Add(5, 6) #similar to previous instances, call package from myfunc, using myfunc. + name of function.
func = myfunc.func(10, 4) #results of Add, Product, Diff are stored in a tuple (same order are listed in the function).
Matrix = myfunc.Func_Matrix(10, 9) 

print(f'Add: {Add_Func},\n\n func: {func},\n\n Matrix: {Matrix}')

Add: 11,

 func: (14, 40, 6),

 Matrix: [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.]
 [ 0.  2.  4.  6.  8. 10. 12. 14. 16.]
 [ 0.  3.  6.  9. 12. 15. 18. 21. 24.]
 [ 0.  4.  8. 12. 16. 20. 24. 28. 32.]
 [ 0.  5. 10. 15. 20. 25. 30. 35. 40.]
 [ 0.  6. 12. 18. 24. 30. 36. 42. 48.]
 [ 0.  7. 14. 21. 28. 35. 42. 49. 56.]
 [ 0.  8. 16. 24. 32. 40. 48. 56. 64.]
 [ 0.  9. 18. 27. 36. 45. 54. 63. 72.]]


In [9]:
Add = []
Product = []
for x in range(100):
    result = myfunc.Func(x) #calling function from myfunc, and obtaining output for a range of inputs.
    Add.append(result[0])
    Product.append(result[1])

print(f'Add: {Add}, \n\n Product: {func}')

Add: [0, 2, 6, 12, 20, 30, 42, 56, 72, 90, 110, 132, 156, 182, 210, 240, 272, 306, 342, 380, 420, 462, 506, 552, 600, 650, 702, 756, 812, 870, 930, 992, 1056, 1122, 1190, 1260, 1332, 1406, 1482, 1560, 1640, 1722, 1806, 1892, 1980, 2070, 2162, 2256, 2352, 2450, 2550, 2652, 2756, 2862, 2970, 3080, 3192, 3306, 3422, 3540, 3660, 3782, 3906, 4032, 4160, 4290, 4422, 4556, 4692, 4830, 4970, 5112, 5256, 5402, 5550, 5700, 5852, 6006, 6162, 6320, 6480, 6642, 6806, 6972, 7140, 7310, 7482, 7656, 7832, 8010, 8190, 8372, 8556, 8742, 8930, 9120, 9312, 9506, 9702, 9900], 

 Product: (14, 40, 6)


In [10]:
Fibonacci_Value = myfunc.Fibonacci(15)

Fib_Seq = []
for x in range(21): Fib_Seq.append(myfunc.Fibonacci(x)) 

print(Fib_Seq)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765]


## Interesting Examples

1. Fibonacci Sequence
https://www.mathsisfun.com/numbers/fibonacci-sequence.html

In [11]:
import numpy as np

def Fib(x):
    q = np.arange(x)
    if x == 0:
        fib = 0
    elif x == 1:
        fib = 1
    else: 
        y = [0,1]
        for i in q[1:]:
            y.append(y[-2] + y[-1])
        fib = y[-1]
    return fib 

a = 100
c = np.arange(1,a)
Fibonacci = []
Fib_Ratio = []
for i in range(len(c)-1):
    Fibonacci.append(Fib(c[i]))
    Fib_Ratio.append(Fib(c[i+1])/Fib(c[i]))


print(f'Sequence: {Fibonacci}, \n\n  Ratio: {Fib_Ratio}')


Sequence: [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733, 1134903170, 1836311903, 2971215073, 4807526976, 7778742049, 12586269025, 20365011074, 32951280099, 53316291173, 86267571272, 139583862445, 225851433717, 365435296162, 591286729879, 956722026041, 1548008755920, 2504730781961, 4052739537881, 6557470319842, 10610209857723, 17167680177565, 27777890035288, 44945570212853, 72723460248141, 117669030460994, 190392490709135, 308061521170129, 498454011879264, 806515533049393, 1304969544928657, 2111485077978050, 3416454622906707, 5527939700884757, 8944394323791464, 14472334024676221, 23416728348467685, 37889062373143906, 61305790721611591, 99194853094755497, 160500643816367088, 259695496911122585, 420196140727489673, 679891637638612258, 11

2. Prime Numbers
https://www.cuemath.com/numbers/prime-numbers/

In [12]:

def Prime_Numbers(x):
    Prime = []
    for i in range(1, x+1):
        Factors = []
        for j in range(1, i+1):
            div = i/j
            modu = i%j
            if modu == 0:
                f = j 
                Factors.append(f)
        if len(Factors) == 1:
            Prime.append(Factors[-1])
        if len(Factors) == 2:
            Prime.append(Factors[-1])
        N_Prime = len(Prime)
    return Prime, N_Prime


X = 200
print(f'Prime Numbers till {X}: ' + str(Prime_Numbers(X)[0]), f'Number of Primes till {X}: ' + str(Prime_Numbers(X)[1]))

Prime Numbers till 200: [1, 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199] Number of Primes till 200: 47


3. Pascal's Triangle
https://www.mathsisfun.com/pascals-triangle.html

In [13]:
import numpy as np

def Pascal_Triangle(x):
    Pascal = []
    for i in range(x):
        if i == 0:
            p = [1]
            Pascal.append(p)
        elif i == 1:
            p = [1, 1]
            Pascal.append(p)
        else:
            pascal = []
            for j in range(1,len(Pascal[-1])):
                q = Pascal[-1][j] + Pascal[-1][j-1]
                pascal.append(q)
            p = [1] + pascal + [1]
            Pascal.append(p)
    return Pascal

print(Pascal_Triangle(10))


[[1], [1, 1], [1, 2, 1], [1, 3, 3, 1], [1, 4, 6, 4, 1], [1, 5, 10, 10, 5, 1], [1, 6, 15, 20, 15, 6, 1], [1, 7, 21, 35, 35, 21, 7, 1], [1, 8, 28, 56, 70, 56, 28, 8, 1], [1, 9, 36, 84, 126, 126, 84, 36, 9, 1]]
