# Loops and Statements 

#### For Loops

For loops iterate through code in its body for a set number of times, until a predetermined condition is no longer met. 

It is useful for a large number of repetitive tasks over a sequence/list of variables.


for item (each element) in list

    for: defines the type of loop.
    item: elements that will be called upon by the loop.
    in: indicates from where the elements are called (in the above example, elements are called from List). 

Indentations are VERY important:

    Indentations highlight the creation of a block, which comprises of code that will be run under the loop.
    All components of the block require similar indentations. 

In [1]:
List = [1, 2, 3, 4, 5, 6] 
for item in List: 
    print(f'Iteration{item}: {item + 1}') #adds 1 to each item in List and prints it. 

Iteration1: 2
Iteration2: 3
Iteration3: 4
Iteration4: 5
Iteration5: 6
Iteration6: 7


Example: Use a For Loop to add 1 to each item in the list. 

    new_item: Variable that stores the operation of the loop on each item (gets updated after every iteration).
    
    Important to create a blank list to store these values. 
            New_List: starts of as a blank list.`

In [2]:
List = [1, 2, 3, 4, 5, 6]
New_List = [] 
for item in List:
    new_item = item + 1  
    New_List.append(new_item)  #append function adds the value of 'new_item' after every iteration to New_List.

print(New_List)

[2, 3, 4, 5, 6, 7]


Example: Iterating through Index values

        For Loop to add ‘10’ to each element in the Array, and store them in a new list, labelled ‘Array_Updated’.
        Loop is iterating through the array index: ‘Array’ consists of 10 elements between the index range of 0 and 9.
        Allow the loop to iterate through all ‘i’ values within the range of 0 and len(Array)
        len(Array) gives the length of the array = 10, and range(len(Array)) returns values between 0 and 9.



In [3]:
import numpy as np
Array = np.random.normal(0,1, size = 10)
Array_Updated = []
for i in range(len(Array)):         
    Array_Updated.append(Array[i] + 10)

print(f'Array: {Array}, Array_Updated: {Array_Updated}')


Array: [ 2.34566873 -0.26754833  1.66828057  0.05297982  0.8403428   1.16182526
  0.3832281   0.44528314 -0.45900724  1.02701563], Array_Updated: [12.345668733076167, 9.732451671657985, 11.668280565342481, 10.05297981894864, 10.840342796828207, 11.161825264375103, 10.38322809827313, 10.445283139489986, 9.540992756728581, 11.027015631331125]


Change in range of i: it ranges from 0, to len(Array), at increments of 2.

Only element with indices correspodning to the range (increments of 2) are selected within the loop.

Array_Updated will comprise of only 5 elements. 

In [4]:
import numpy as np
Array = np.random.normal(0,1, size = 10)
Array_Updated = []
for i in range(1, len(Array), 2):
    Array_Updated.append(Array[i] + 10)
    
print(f'Array: {Array}, Array_Updated: {Array_Updated}')

Array: [-0.25254921 -2.39101379 -0.51027207 -0.60587901 -0.67944528  1.43585066
 -0.35560254  1.04756207 -0.97724232  0.01343207], Array_Updated: [7.60898621349202, 9.39412098987632, 11.435850663421041, 11.047562065578624, 10.013432072284477]


Example: Cumulative Sum using a For Loop

    Enumerate: Allows a loop to iterate by tracking the count (index, i) of each element in the array, and its corresponding value.

    Good Practice: Create an array/matrix of zeros, to be overwritten from the output of each loop iterations (Extremely helpful when utilising nested loops).


In [5]:
import numpy as np
Array = np.random.normal(0,1, size = 10)
Cumulative_Sum = np.cumsum(Array) #Cumulative Sum at each index

#Aim: Replicate np.cumsum using for loops. 
Cum_Sum = np.zeros(len(Array)) #create a zeros matrix to be overwritten 
cumsum = 0 #initialise the variable, such that at the first iteration, there is something to add to. 
for i, value in enumerate(Array):
    cumsum += value
    Cum_Sum[i] = cumsum

print(f'Numpy: {Cumulative_Sum}, Loop: {Cum_Sum}')    

Numpy: [ 0.71548554  0.66139068  0.2250574  -0.19191976 -0.19948063  1.86066944
  1.44019396  1.74956801  1.83272755  4.06148333], Loop: [ 0.71548554  0.66139068  0.2250574  -0.19191976 -0.19948063  1.86066944
  1.44019396  1.74956801  1.83272755  4.06148333]


#### Nested For Loops

Example: Overwrite a zero matrix, by iterating through each element by location.

In [6]:
import numpy as np
Matrix = np.zeros([5,5])
size = Matrix.shape #store the size(number of rows and columns in a tuple)

for i in range(size[0]): #iterate through rows
    for j in range(size[1]): #iterate through columns within each row
        Matrix[i,j] = i*j #Each element is the product of the index of rows and columns, corresponding to its location.
        #Matrix is overwritten.
print(Matrix)

[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  2.  4.  6.  8.]
 [ 0.  3.  6.  9. 12.]
 [ 0.  4.  8. 12. 16.]]


#### While Loops

        While Loops execute a block of statements repeatedly, till a given condition is satisfied. 

        If false (once the condition is false), the loop is terminated. 

In [7]:
i = 0  #It is important to define an initial value for ‘i’, as a starting point for the loop.
List = []
while i < 20: 
    List.append(i**2)
    i +=1   #After each iteration, 1 is added to i, such that ‘i < 20’ is revaluated on the updated ‘i’. 
#Loop is designed to conduct operations for values of ‘i’ that are less than 20.
    #If the condition is met (i < 20), then the outcome of the operation ‘i**2’ will be appended to ‘List’. 


Possibility of an Infinite Loop (depends on the condition) [DO NOT RUN]

In [ ]:
"""
i = 21
List = []
while i > 20:
    List.append(i**2)
    i +=1

#Condition has been altered (from the previous) to ‘i > 20’, with the initial value set at 21.

#Given that 1 will be added to ‘i’ at the end of each iteration, this loop will never be automatically terminated.
"""

#### Nested While Loops

    Designed to perform the same task as seen with nested for loops. 

    Example: Overwrite a zero matrix, by iterating through each element by location.

In [9]:
import numpy as np 
Matrix = np.zeros([5, 5])
Size = Matrix.shape
i = 0
while i < Size[0]: #‘i’- row index of ‘Matrix’, the loop terminates when i >= number of rows (final index value = no.of rows – 1).
    j = 0 #Initial of ‘j’ defined before the start of the ‘j’ loop, within under the ‘i’ loop (pay attention to the indentation).
    while j < Size[0]: #‘j’- column index of ‘Matrix’, the loop terminates when i >= number of columns.
        Matrix[i,j] = i*j
        j = j + 1 #j is updated within the i loop: While loop goes through every column, within each row.
    i = i + 1

print(Matrix)

[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  2.  4.  6.  8.]
 [ 0.  3.  6.  9. 12.]
 [ 0.  4.  8. 12. 16.]]


## Conditional Statements

    - Allow to control the flow of a programme based on specified conditions. 

    - Incorporate decision making during the execution of codes. 

#### 1. if statements

Execuete a block of code, given that a certain condition is satisfied. 

Example: Condition: 'if x = 5', Output: print('x = 5')
        
        - if true, 'x = 5' will be displayed.

        - When stating an equality condition, use '==' (equality operator), not '=' (assignment operator).


In [10]:
x = 5
if x == 5:
    print('x = 5')
    

x = 5


#### 2. if-else statements

Executes a block of codes if the statement is true, and another block of code, if false (else scenario). 

Example: ‘x’ is set to equal 5, and an if statement is presented with the condition: ‘if x == 5:’, then print: ‘x = 5’.
    - if x does not equal to 5, then output will be ‘x does not equal 5’.

In [11]:
x = 5
if x == 5:
    print('x = 5')
else: 
    print('x does not equal 5')

x = 5


#### 3. if-elif-else statements

Execution over 2 conditions (or more), and an alternative (else-condition), during which neither hold true. 

Example: if x > 5: 'x > 5', elif if x < 5: 'x < 5', else (x == 5): 'x==5'

        Condition 1: if-statement x > 5
        Condition 2 elif-statement x < 5 
        Alternative, else statement: x == 5 (condition 1 and 2 do not hold).

In [12]:
x = 5
if x > 5:  #Condition 1
    print('x > 5')
elif x < 5: #Condition 2 
        print('x < 5')
else:  #Alternative, else statement
    print('x == 5')

x == 5


#### 'if-elif-else' statements and 'for' loops

In [13]:
import numpy as np 
Rand = np.random.rand(500) #500 uniformly distributed random values between 0 and 1.
Rand_1 = []
Rand_2 = []
Rand_3 = []
for i in range(len((Rand))):
    if Rand[i] < 0.25: 
        Rand_1.append(Rand[i]) #if value < 0.25 append to Rand_1
    elif (Rand[i] >= 0.25) and (Rand[i] < 0.75): #two conditions: write each condition within (), with 'and' between them
        Rand_2.append(Rand[i]) #if 0.25 <= value < 0.75 append to Rand_2
    else:
        Rand_3.append(Rand[i]) #if value > 0.75 append to Rand_3

#Number of variable in each list, based on conditions.
Count = [len(Rand_1), len(Rand_2), len(Rand_3)]
print(Count)

[129, 244, 127]
