# Session 2: Introduction to NumPy 

NumPy is a Numerical Computing Python Library used for conducting mathematical operations of large, multidimensional arrays. 

    - Arrays and Operations are vectorised: No explicit Looping or Indexing is required, making it readable and similar to standard mathematical notation. 

    - Arrays can be created in any dimensioms: Allows for mathematical, and statistical operations, that are frequently used in scientific computing. 

    - Operations are performed much faster and more efficiently using NumPy: Less Memory and Storage space is occupied. 

NumPy is designed to work seamlessly with other scientific computing libraries in Python,  allowing for a wider range of advanced computations and data visualisation.

Applications of NumPy: Data Analysis and Manipulation, Scientific Computing and Simulations, Machine Learning and AI, etc.

For more information: https://numpy.org/doc/stable/user/index.html	




In [6]:

#pip install numpy
import numpy as np


## Basic Array Operations

Array is a contrainer that stores more than one item.

    - Very similar to Lists, however, arrays behave very differently when part of NumPy. 


Vectorised Operations are supported by NumPy arrays, but NOT by Lists. 

    - NumPy arrays makes calculations highly efficient.


Arrays are not mutuable, and can only comprise of ONE type of element.

Suggestion: Use lists for mutable operations, convert them to NumPy arrays for calculations. 


### Creating Arrays


#### Step I: Create a List
In the example below, two lists (A and B) are created.

In [7]:
A = [4, 5, 6]
B = [1, 2, 3]
print(f'A = {A}\nB = {B}')

A = [4, 5, 6]
B = [1, 2, 3]


Lists do not support vectorised operations, placing the '+' operator would join them, rather than conducting an additive operation.

In [8]:
C = A + B
print (f'C = {C}')

C = [4, 5, 6, 1, 2, 3]


#### Step 2: Call the 'array' function from Numpy using np.array()

Convert both Lists into Arrays

In [9]:
Array_A = np.array(A)  #call 'array' function from numpy 
Array_B = np.array(B)

print(f'Array_A = {Array_A}\nArray_B = {Array_B}')

Array_A = [4 5 6]
Array_B = [1 2 3]


#### Step 3: Conduct Operation of Choice

Operation: Addition 

In [10]:
Add = Array_A + Array_B

print(f'Add = {Add}')

Add = [5 7 9]


Operation: Subtraction

In [11]:
Subtract = Array_A - Array_B 
print(f'Subtract = {Subtract}')

Subtract = [3 3 3]


Operation: Multiplication

In [12]:
Multiply = Array_A * Array_B
print(f'Multiply = {Multiply}')

Multiply = [ 4 10 18]


Operation: Division

In [13]:
Divide = Array_A / Array_B
print(f'Divide = {Divide}')

Divide = [4.  2.5 2. ]


Operation: Floor Division

In [14]:
Floor_Div = Array_A//Array_B
print(f'Floor_Div = {Floor_Div}')

Floor_Div = [4 2 2]


Operation: Modulo

In [15]:
Modulo = Array_A % Array_B
print(f'Modulo = {Modulo}')

Modulo = [0 1 0]


Operation: Power

In [16]:
Power = Array_A ** Array_B
print(f'Power = {Power}')

Power = [  4  25 216]


## Indexing and Slicing Arrays

Create an Array using the arange function: Similar to  np.array(range(n)), for n being an integer.

In [17]:
Array = np.arange(0,100)
print(f'Array = {Array}')

Array = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


Elements corresponding with index 1 to 10.

In [18]:
Array[1:10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Elements corresponding with index 1 to 50, at increments of 10.

In [19]:
Array[1:50:10]

array([ 1, 11, 21, 31, 41])

Addition (or any basic operation) with Slicing: Make sure both arrays have the same dimensions (check using .shape).

In [20]:
Array_1 = Array[1:40]
Array_2 = Array[41:80]

Shape_1 = Array_1.shape
Shape_2 = Array_2.shape

print(f' Array_1 = {Array_1}, Shape = {Shape_1}\n\n Array_2  = {Array_2}, Shape = {Shape_2}')

 Array_1 = [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39], Shape = (39,)

 Array_2  = [41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64
 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79], Shape = (39,)


In [21]:
Array_sum = Array_1 + Array_2
Array_sum_shape = Array_sum.shape

print(f' Array_sum = {Array_sum}, Shape = {Array_sum_shape}')

 Array_sum = [ 42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76
  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106 108 110 112
 114 116 118], Shape = (39,)


## Creating a Matrix (2D-Array)

#### Step I: Define each row as a List.
The current example aims to create a 3 x 6 Matrix.

In [22]:
row_1 = [2, 4, 5, 4, 3, 2]
row_2 = [4, 6, 7, 8, 7, 3]
row_3 = [8, 3, 2, 1, 4, 7 ]

print(f' row_1 = {row_1}\n row_2 = {row_2}\n row_3 = {row_3}')

 row_1 = [2, 4, 5, 4, 3, 2]
 row_2 = [4, 6, 7, 8, 7, 3]
 row_3 = [8, 3, 2, 1, 4, 7]


#### Step 2: Create an Array

In [23]:
Matrix_1 = np.array([row_1, row_2, row_3])
Matrix_1_Shape = Matrix_1.shape

print(f' Matrix_1 = {Matrix_1}, Shape = {Matrix_1_Shape}')

 Matrix_1 = [[2 4 5 4 3 2]
 [4 6 7 8 7 3]
 [8 3 2 1 4 7]], Shape = (3, 6)


## Basic Matrix Operations

Create another 3 x 6 matrix

In [24]:
Matrix_2 = np.array([[1, 2, 4, 2, 5, 8], [3, 5, 7, 6, 9, 8], [4, 6, 7, 7, 8,7]])
Matrix_2_Shape = Matrix_2.shape 


print(f' Matrix_2 = {Matrix_2}, Shape = {Matrix_2_Shape}')

 Matrix_2 = [[1 2 4 2 5 8]
 [3 5 7 6 9 8]
 [4 6 7 7 8 7]], Shape = (3, 6)


Operation: Addition

In [25]:
Add_Matrix = Matrix_1 + Matrix_2
print(f' Add_Matrix = {Add_Matrix}')

 Add_Matrix = [[ 3  6  9  6  8 10]
 [ 7 11 14 14 16 11]
 [12  9  9  8 12 14]]


Operation: Subtraction

In [26]:
Subtract_Matrix = Matrix_1 - Matrix_2
print(f' Subtract_Matrix = {Subtract_Matrix}')

 Subtract_Matrix = [[ 1  2  1  2 -2 -6]
 [ 1  1  0  2 -2 -5]
 [ 4 -3 -5 -6 -4  0]]


Operation: Multiplication (Element by Element)

In [27]:
Multiplication_Matrix = Matrix_1 * Matrix_2 
print(f' Multiplication_Matrix = {Multiplication_Matrix}')

 Multiplication_Matrix = [[ 2  8 20  8 15 16]
 [12 30 49 48 63 24]
 [32 18 14  7 32 49]]


Operation: Division (Elemnet by Element)

In [28]:
Division_Matrix = Matrix_1/Matrix_2
print(f' Division_Matrix = {Division_Matrix}')

 Division_Matrix = [[2.         2.         1.25       2.         0.6        0.25      ]
 [1.33333333 1.2        1.         1.33333333 0.77777778 0.375     ]
 [2.         0.5        0.28571429 0.14285714 0.5        1.        ]]


Operation: Matrix Multiplication 
Ensure the dimensions of the matrices are valid for multiplication.

Step I: Transpose Matrix_2 to Matrix_2T

Step II: Matrix_1 (3 x 6) x Matrix_2T (6 x 3)

In [29]:
Matrix_2T = np.transpose(Matrix_2)
Mat_Mul = np.matmul(Matrix_1, Matrix_2T)

print(f'Matrix_2_Transpose = {Matrix_2T}\n\nMat_Mul = {Mat_Mul}')

Matrix_2_Transpose = [[1 3 4]
 [2 5 6]
 [4 7 7]
 [2 6 7]
 [5 9 8]
 [8 8 7]]

Mat_Mul = [[ 69 128 133]
 [119 226 234]
 [100 151 152]]


## Slicing and Indexing Matrices

All elements in the first row (index = 0) of Matrix_1

In [30]:
Matrix_1[0]

array([2, 4, 5, 4, 3, 2])

All elements in all the row, corresponding to the first column (index = 0)

In [31]:
Matrix_1[:,0]

array([2, 4, 8])

Element corresponding to row index 1, and column index 2

In [32]:
Matrix_1[1, 2]

7

Element indexed at 2, within row indexed at 1

In [33]:
Matrix_1[1][2]

7

Element within rows at index 0 to 2 (excluding 2), and columns 4 to 6 (excluding 6)

In [34]:
Matrix_1[0:2, 4:6]

array([[3, 2],
       [7, 3]])

From Matrix_1, includes only variables that are greater than 4

In [35]:
Matrix_1[Matrix_1>4]

array([5, 6, 7, 8, 7, 8, 7])

From Matrix_1, includes only variables that are greater than 3, and less than equal to 6

In [36]:
Matrix_1[(Matrix_1 > 3) & (Matrix_1 <= 6)] 

array([4, 5, 4, 4, 6, 4])

## Linear Algebra

#### np.linalg(): Designed to allow efficient implementation of basic linear algebra algorithms.

Create two (3 x 3) Matrices: Matrix_A and Matrix_B

In [37]:
Matrix_1 = np.array([[2, 4, 5], [4, 6, 7], [8, 3, 2]]) 
Matrix_2 = np.array([[1, 2, 4], [3, 5, 7], [4, 6, 7]]) 

Operation: Transpose

In [38]:
Matrix_1T = np.transpose(Matrix_1)
print(f' Matrix_1T = {Matrix_1T}')

 Matrix_1T = [[2 4 8]
 [4 6 3]
 [5 7 2]]


Operation: Eigenvalue(s) and Eigenvector

In [39]:
Eigen_Value, Eigen_Vector = np.linalg.eig(Matrix_1)
print(f' Eigen_Value = {Eigen_Value}, Eigen_Vector = {Eigen_Vector}')

 Eigen_Value = [13.57659974 -3.69616603  0.11956629], Eigen_Vector = [[-0.46949956 -0.42217514  0.16395894]
 [-0.7200105  -0.40964917 -0.79946267]
 [-0.5110333   0.80867528  0.57790735]]


Operation: Rank

In [40]:
Rank = np.linalg.matrix_rank(Matrix_1) 
print(f' Rank  = {Rank}')

 Rank  = 3


Operation: Trace (sum of diagonal)

In [41]:
Trace = np.trace(Matrix_1)
print(f' Trace = {Trace}')

 Trace = 10


Operation: Determinant

In [42]:
Det = np.linalg.det(Matrix_1)
print(f' Det = {Det}')

 Det = -6.000000000000011


Operation: Inverse

In [43]:
Inv = np.linalg.inv(Matrix_1)
print (f' Inv = {Inv}')

 Inv = [[ 1.5        -1.16666667  0.33333333]
 [-8.          6.         -1.        ]
 [ 6.         -4.33333333  0.66666667]]


Operation: Identity Matrix (Checking Inverse Output)

In [44]:
Iden_Matrix_1 = np.matmul(Matrix_1, Inv)
print(f' Iden_Matrix_1 = {Iden_Matrix_1}')

 Iden_Matrix_1 = [[ 1.00000000e+00  2.66453526e-15 -2.22044605e-16]
 [-3.55271368e-15  1.00000000e+00 -2.22044605e-16]
 [ 0.00000000e+00 -1.77635684e-15  1.00000000e+00]]


Solve for A * X = B, where A = Matrix_1, B = Matrix_2, hence X = B * Inverse (A) 

In [45]:
Solve = np.linalg.solve(Matrix_1, Matrix_2)
print(f' Solve = {Solve}')

 Solve = [[-0.66666667 -0.83333333  0.16666667]
 [ 6.          8.          3.        ]
 [-4.33333333 -5.66666667 -1.66666667]]


Use Solve to obtain Matrix_2, from previous solution and Matrix_1

In [46]:
Matrix_2_Solve = np.matmul(Matrix_1, Solve)
print(f' Matrix_2_Solve = {Matrix_2_Solve}')

 Matrix_2_Solve = [[1. 2. 4.]
 [3. 5. 7.]
 [4. 6. 7.]]


Operation: Inner Product 

In [47]:
Inner_Product = np.inner(Matrix_1, Matrix_2)
print(f' Inner_Product = {Inner_Product}')

 Inner_Product = [[ 30  61  67]
 [ 44  91 101]
 [ 22  53  64]]


Operation: Outer Product

In [48]:
Outer_Product = np.outer(Matrix_1, Matrix_2)
print(f' Outer_Product = {Outer_Product}')

 Outer_Product = [[ 2  4  8  6 10 14  8 12 14]
 [ 4  8 16 12 20 28 16 24 28]
 [ 5 10 20 15 25 35 20 30 35]
 [ 4  8 16 12 20 28 16 24 28]
 [ 6 12 24 18 30 42 24 36 42]
 [ 7 14 28 21 35 49 28 42 49]
 [ 8 16 32 24 40 56 32 48 56]
 [ 3  6 12  9 15 21 12 18 21]
 [ 2  4  8  6 10 14  8 12 14]]


## Special Matrices

Matrix of Ones: np.ones()

In [49]:
ones = np.ones([4,5]) 
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Matrix of Zeros: np.zeros()

In [50]:
zeros = np.zeros([6, 5]) 
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Identity Matrix: np.eye()

In [51]:
eye = np.eye(10)
print(eye)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


### Generating a Matrix of Random Values

For more information for generating random variables, using other distributions: https://numpy.org/doc/stable/reference/random/index.html

Matrix with random sample from a uniform distribution over [0, 1).

In [52]:
rand = np.random.rand(3, 2)
print(rand)

[[0.28402367 0.41810236]
 [0.56368763 0.8056928 ]
 [0.97200017 0.61184876]]


Convert Matrix to List of Lists: Each row is converted into a seperate list.

In [53]:
rand_list = rand.tolist()
print(rand_list) 

[[0.284023669661308, 0.4181023573916549], [0.5636876334162807, 0.805692800073761], [0.9720001667247051, 0.6118487568566215]]


Matrix with random interger sample from a uniform distribution over [2, 10)

In [54]:
rand_int = np.random.randint(2, 10, size = (2, 3))
print(rand_int)

[[7 3 2]
 [8 8 6]]


Matrix of random variables following normal distribution, with mean 0, and std = 1. 

In [55]:
rand_norm = np.random.normal(0, 1, size  = (10, 10))
print(rand_norm)

[[ 1.35159812  0.38342195 -0.45268038  0.94364923 -0.42208241 -0.72982609
  -0.88403279 -0.68185602 -2.0337128   0.37130416]
 [-0.377188    1.68979135  0.89220175 -0.33817804 -0.90864275  0.15145464
   0.40024571  0.80389122 -0.29935574 -1.01642145]
 [-0.84143808  1.69322717  0.64239622  0.18608698 -2.71301504 -2.43941826
   0.02073793 -1.68752445 -1.37541414 -0.44999115]
 [ 0.65458475  1.00580528  0.62906274  0.21789659 -1.39899398  0.0945999
  -1.09968018 -1.60204221  1.72658764 -1.08292483]
 [ 0.20301971  0.96154237 -0.09845143 -1.17999689  2.37062726  0.01109736
   0.08291529 -2.41858093 -1.39149606 -0.88431724]
 [-0.14426998  1.48133161  2.01659079  0.18858843  0.57617017 -0.62100688
  -1.55262802 -1.14674081  0.37094792  0.66910004]
 [ 0.26150034 -2.10357724 -1.4319521  -0.35861613 -0.00759823 -0.54294032
  -1.00911057 -0.47794997 -1.17420848 -2.18556661]
 [-0.43785407  0.10232386  0.68233921  0.61396268 -0.86296698  0.10539961
  -0.22115821  1.36449219 -0.31261904 -0.57518939]
 

Using np.random.standard_normal() function: no need to define mean and std (by default considered as 0 and 1).

In [56]:
rand_std_norm = np.random.standard_normal(size = (10, 10))
print(rand_std_norm)

[[-0.89610235  1.89124303  0.52895465  0.37497222  1.39896074  0.66015958
  -1.23966588  0.65837566 -0.51437418  1.30463473]
 [ 0.80888025 -1.7823724   0.37642591 -0.42864293  0.42774589 -0.49838759
  -0.48713581  0.60350892 -0.66343049 -0.55812871]
 [ 0.22316022  0.37124064  0.2027595  -0.21333142  1.45141688 -0.85747165
   0.37832405  0.08584784 -0.02312869  2.64120121]
 [ 1.16717545 -1.12287627 -0.15137227 -2.10309178 -0.3229612  -2.64855221
  -0.11470757  0.95260929  0.07193338  1.14302705]
 [-1.39126371 -0.8987791   0.02431583  1.3435666   0.36534044  1.66946437
   0.03344819 -1.48851965 -0.39895822  0.1145084 ]
 [-0.00698014  0.68514102 -0.79887768 -1.72688668  1.2409174   0.91511393
   0.06128653 -0.63620412  0.61813246  0.52834146]
 [-0.19970835  0.18126589 -2.38076928 -0.3801994  -1.33776657  1.82935186
   1.15952098  0.82565595  1.05744057 -0.86380386]
 [ 0.78803976 -0.49430473 -0.89326998 -0.03988117 -0.69045275  0.06491399
  -0.58687749  0.43438685  1.05596394  0.05039105]


## Statistical Operations

Note: To ensure reproducable results, ensure the seed is set, such that the generation of random elememts is consistent.

In [57]:
np.random.seed(1) 
rand_1 = np.random.normal(0,1, size = (50, 10)) #50 x 10 matrix.


Mean and Standard Deviation of all matrix elements.

In [58]:
Mean_rand_1 = rand_1.mean()
Std_rand_1 = rand_1.std()
print(Mean_rand_1, Std_rand_1)  #As numbers approach infinity, mean tends to 0, and std tends to 1.

0.053436894256306586 0.98840825928265


Linear Equation

Recall, NumPy allows for vectorised operations: constant 'b' is multiplied to all components of the matrix, and 'a' is added to the product.

In [59]:
a = 1.5
b = 3.5
Y = a + b*rand_1 

print(Y)

[[ 7.18520877e+00 -6.41147448e-01 -3.48601133e-01 -2.25539018e+00
   4.52892670e+00 -6.55538544e+00  7.60684117e+00 -1.16422415e+00
   2.61663684e+00  6.27203686e-01]
 [ 6.61737778e+00 -5.71049248e+00  3.71539786e-01  1.55809759e-01
   5.46819305e+00 -2.34961944e+00  8.96501274e-01 -1.57250446e+00
   1.64774811e+00  3.53985325e+00]
 [-2.35216712e+00  5.50653298e+00  4.65556752e+00  3.25873019e+00
   4.65299582e+00 -8.93047507e-01  1.06988421e+00 -1.77519302e+00
   5.62391721e-01  3.35624413e+00]
 [-9.20812631e-01  1.11362656e-01 -9.05104450e-01 -1.45821975e+00
  -8.49361458e-01  1.45567390e+00 -2.41058622e+00  2.32045494e+00
   7.30930762e+00  4.09715456e+00]
 [ 8.28575567e-01 -1.60670137e+00 -1.11505403e+00  7.42359110e+00
   1.67782714e+00 -7.29484763e-01  2.16820420e+00  8.85089298e+00
   1.92055633e+00  3.66021088e+00]
 [ 2.55059612e+00  2.67125537e-01 -2.49881369e+00  2.77300472e-01
   7.68870183e-01  3.55318117e+00  4.43644195e+00  4.75885728e+00
   2.49955564e+00  4.59799407e+00

Mean 

In [60]:
Y_mean = Y.mean() 
Y_column_mean = Y.mean(axis = 0) 
Y_row_mean = Y.mean(axis = 1)

print(f'Entire Mean = {Y_mean}, Column Mean = {Y_column_mean}, Row Mean = {Y_row_mean}')

Entire Mean = 1.687029129897073, Column Mean = [1.48453766 1.58901932 1.94361221 2.5272385  1.80156651 0.95081938
 1.5583801  1.508348   1.75946777 1.74730184], Row Mean = [ 1.16000688  0.90644066  1.80419389  0.87498692  2.3078618   2.12111087
  3.09837262  1.11322781  2.00716466  1.72703371  1.64076012  0.7449799
  2.70715035  1.12535225  2.76328861  1.31168273  1.58846347  2.81461168
  1.8922244   3.75930369  0.45656127  1.57795073  2.67919129  1.09639896
  0.90005097  1.62240294  1.64968677  2.62526774  1.22962563  1.50663
  1.34890021  3.2575537   2.02665448 -1.05861259  1.35634134  1.55136967
  0.77328854  2.4462948   0.65188203  1.93364139  1.01585884  0.74300368
  2.13941059  4.39039081  1.58229147  1.29536356  2.4484026   0.74041811
  3.03483503 -0.13781511]


Standard Deviation

In [61]:
Y_std = Y.std()
Y_column_std = Y.std(axis = 0)
Y_row_std = Y.std(axis = 1)
print(f'Entire Std = {Y_std}, Column Std = {Y_column_std}, Row Std = {Y_row_std}')

Entire Std = 3.459428907489275, Column Std = [2.97346553 3.60089504 3.5645046  3.2725246  3.54712098 3.30214777
 3.56644699 3.61255573 3.37389471 3.5183858 ], Row Std = [4.16814493 3.49698944 2.71885264 2.83546094 3.31407852 2.25479654
 3.66530979 3.24820904 1.5727083  1.96609679 2.46389482 3.29374845
 4.26241521 2.55811606 1.24638478 4.04466578 3.68656798 3.27355138
 2.31367464 3.04097666 4.63791475 3.20068897 3.91789615 3.58220131
 3.27595251 4.70148274 2.5528363  3.59453155 1.89591747 1.88006466
 3.80494356 3.95613694 2.66597573 4.73178455 2.14441169 2.22628309
 4.09707343 3.968158   2.30204102 4.42013037 3.5113932  5.22185296
 3.0882317  1.93751875 3.58011632 2.80824138 2.7557629  3.59319067
 3.3898275  3.18611929]


Minimum and Maximum Value

In [62]:
Y_min = Y.min()
Y_column_min = Y.min(axis = 0)
Y_row_min = Y.min(axis = 1)

Y_max = Y.max()
Y_column_max = Y.max(axis = 0)
Y_row_max = Y.max(axis = 1)

print(f'Entire Min = {Y_min}, Column Min = {Y_column_min}, Row Min = {Y_row_min}\n\n Entire Max = {Y_max}, Column Max = {Y_column_max}, Row Max = {Y_row_max}')
#\n - next line.

Entire Min = -8.27579750051289, Column Min = [-3.55439832 -7.02193217 -8.2757975  -3.38817149 -6.9472605  -6.55538544
 -5.99863355 -8.23887064 -7.27254228 -5.89957373], Row Min = [-6.55538544 -5.71049248 -2.35216712 -2.41058622 -1.60670137 -2.49881369
 -3.38773717 -5.57770426 -0.847318   -0.73555643 -2.33219146 -4.15520324
 -5.00293653 -2.80520347  0.8470058  -7.02193217 -5.13726323 -0.76420841
 -2.95395564 -4.19603419 -4.66240996 -3.19936526 -2.76910539 -4.35968533
 -3.38817149 -8.2757975  -3.83988111 -3.54306609 -2.40764506 -1.84398842
 -3.64904924 -1.53719037 -1.39134101 -7.27254228 -2.61593935 -0.95470549
 -8.23887064 -4.64573974 -3.88577636 -5.05606342 -5.99863355 -6.9472605
 -1.12489366  1.13989474 -4.39420995 -1.65572072 -2.00059216 -5.33236851
 -2.40204868 -6.32980279]

 Entire Max = 12.107999893302107, Column Max = [ 8.73024162  8.69724433 10.34913997  9.15442876 12.10799989 10.07279027
  8.98239824  8.85089298  9.16744905  8.88711769], Row Max = [ 7.60684117  6.61737778  5.50

50th Percentile (median)

In [63]:
Y_P50 = np.percentile(Y, 50)
Y_column_P50 = np.percentile(Y,50, axis = 0)
Y_row_P50 = np.percentile(Y, 50, axis = 1)
print(f'Entire P50 = {Y_P50}, Column P50 = {Y_column_P50}, Row P50 = {Y_row_P50}')

Entire P50 = 1.6357542265981126, Column P50 = [0.83777454 1.46243733 2.26188097 2.68303801 1.69522641 1.19247784
 1.66511022 1.88637301 2.11585301 1.7231152 ], Row P50 = [ 0.13930128  0.63402053  2.1643072  -0.3689994   1.79919174  2.52507588
  3.25253394  2.18273066  2.03966966  1.71163962  1.85349471  1.98381179
  3.60237477  1.26488224  2.8334298   1.11638351  1.5679538   1.18037081
  2.4124538   4.07250257 -1.04250678  1.15455364  1.34348846  1.64238981
  0.18022541  1.73711147  2.19390237  4.29091816  1.74793527  1.25266811
 -0.03807894  3.17973259  1.75672218 -1.32634913  1.01316692  0.82576286
  2.68434506  2.52592996  0.87063823  2.27392395  1.78497855  0.90081967
  1.12969807  4.78045975  1.59669796 -0.4706349   2.16644693  0.41861186
  3.71732614  0.58966468]


Percentile: 1%, 5%, 10%, 25%, 50%, 75%, 90%, 95%, 99%

In [64]:
Percentile_List = [1, 5, 10, 25, 50, 75, 90, 95, 99]
Y_Percentile = np.percentile(Y, Percentile_List) #Percentile values returned in accordance with Percentile_List index. 
Y_column_Percentile = np.percentile(Y, Percentile_List, axis = 0) 
Y_row_Percentile = np.percentile(Y, Percentile_List, axis = 1) 


print(f'Entire % = {Y_Percentile}, Column % = {Y_column_Percentile}, Row % = {Y_row_Percentile}')

Entire % = [-6.55930419 -4.2001087  -2.61815676 -0.66135766  1.63575423  4.09324932
  5.89234926  7.66176232  9.14956307], Column % = [[-3.52428569 -6.37932673 -6.81845637 -2.83310864 -5.99454175 -6.07632166
  -5.81810321 -7.30342739 -5.98540904 -5.86541761]
 [-3.20104201 -4.14476197 -3.39951856 -1.54884949 -3.63769972 -4.69489976
  -5.20803122 -4.78432563 -3.61167408 -4.3499765 ]
 [-2.41234597 -3.24433366 -2.50499186 -1.39802888 -2.77509353 -3.20329616
  -3.61651192 -2.59549058 -2.40857095 -2.66134984]
 [-0.29330982 -0.63429114 -0.30240212 -0.03712551  0.02342982 -0.85215682
  -0.7380409  -1.10602501 -0.52014799 -0.61819976]
 [ 0.83777454  1.46243733  2.26188097  2.68303801  1.69522641  1.19247784
   1.66511022  1.88637301  2.11585301  1.7231152 ]
 [ 3.24783474  4.7038481   4.45692556  4.58953344  3.67107943  3.31972675
   3.65069459  4.19152034  3.64379998  4.14956799]
 [ 5.69955104  5.89401952  5.99840397  7.79856334  5.62073643  4.59353522
   5.73917714  5.68824969  5.52510478  5.6

## Concating and Stacking Operations

Create three different arrays (50 x 1) of random values.

In [65]:
np.random.seed(1) 
rand_1 = np.random.normal(0,1, size = (50, 1))
rand_2 = np.random.normal(0,1, size = (50, 1))
rand_3 = np.random.normal(0,1, size = (50, 1))

### Concatenate

Concatenated to the same column (default axis = 0): Output = 150 x 1 array.

In [66]:
concat_column = np.concatenate((rand_1, rand_2, rand_3))
print(concat_column)

[[ 1.62434536]
 [-0.61175641]
 [-0.52817175]
 [-1.07296862]
 [ 0.86540763]
 [-2.3015387 ]
 [ 1.74481176]
 [-0.7612069 ]
 [ 0.3190391 ]
 [-0.24937038]
 [ 1.46210794]
 [-2.06014071]
 [-0.3224172 ]
 [-0.38405435]
 [ 1.13376944]
 [-1.09989127]
 [-0.17242821]
 [-0.87785842]
 [ 0.04221375]
 [ 0.58281521]
 [-1.10061918]
 [ 1.14472371]
 [ 0.90159072]
 [ 0.50249434]
 [ 0.90085595]
 [-0.68372786]
 [-0.12289023]
 [-0.93576943]
 [-0.26788808]
 [ 0.53035547]
 [-0.69166075]
 [-0.39675353]
 [-0.6871727 ]
 [-0.84520564]
 [-0.67124613]
 [-0.0126646 ]
 [-1.11731035]
 [ 0.2344157 ]
 [ 1.65980218]
 [ 0.74204416]
 [-0.19183555]
 [-0.88762896]
 [-0.74715829]
 [ 1.6924546 ]
 [ 0.05080775]
 [-0.63699565]
 [ 0.19091548]
 [ 2.10025514]
 [ 0.12015895]
 [ 0.61720311]
 [ 0.30017032]
 [-0.35224985]
 [-1.1425182 ]
 [-0.34934272]
 [-0.20889423]
 [ 0.58662319]
 [ 0.83898341]
 [ 0.93110208]
 [ 0.28558733]
 [ 0.88514116]
 [-0.75439794]
 [ 1.25286816]
 [ 0.51292982]
 [-0.29809284]
 [ 0.48851815]
 [-0.07557171]
 [ 1.13162

Concatenated to the same rows: Output = 50 x 3 matrix.

In [67]:
concat_row = np.concatenate((rand_1, rand_2, rand_3), axis = 1) 
print(concat_row)

[[ 1.62434536  0.30017032 -0.44712856]
 [-0.61175641 -0.35224985  1.2245077 ]
 [-0.52817175 -1.1425182   0.40349164]
 [-1.07296862 -0.34934272  0.59357852]
 [ 0.86540763 -0.20889423 -1.09491185]
 [-2.3015387   0.58662319  0.16938243]
 [ 1.74481176  0.83898341  0.74055645]
 [-0.7612069   0.93110208 -0.9537006 ]
 [ 0.3190391   0.28558733 -0.26621851]
 [-0.24937038  0.88514116  0.03261455]
 [ 1.46210794 -0.75439794 -1.37311732]
 [-2.06014071  1.25286816  0.31515939]
 [-0.3224172   0.51292982  0.84616065]
 [-0.38405435 -0.29809284 -0.85951594]
 [ 1.13376944  0.48851815  0.35054598]
 [-1.09989127 -0.07557171 -1.31228341]
 [-0.17242821  1.13162939 -0.03869551]
 [-0.87785842  1.51981682 -1.61577235]
 [ 0.04221375  2.18557541  1.12141771]
 [ 0.58281521 -1.39649634  0.40890054]
 [-1.10061918 -1.44411381 -0.02461696]
 [ 1.14472371 -0.50446586 -0.77516162]
 [ 0.90159072  0.16003707  1.27375593]
 [ 0.50249434  0.87616892  1.96710175]
 [ 0.90085595  0.31563495 -1.85798186]
 [-0.68372786 -2.02220122

## Stacking

Similar to concatanating, but without the need to define the axis.

Vertical Stacking: Stack a Column (similar to np.concatenate, with axis =0).

In [68]:
V_Stack = np.vstack((rand_1, rand_2, rand_3))
print(V_Stack)

[[ 1.62434536]
 [-0.61175641]
 [-0.52817175]
 [-1.07296862]
 [ 0.86540763]
 [-2.3015387 ]
 [ 1.74481176]
 [-0.7612069 ]
 [ 0.3190391 ]
 [-0.24937038]
 [ 1.46210794]
 [-2.06014071]
 [-0.3224172 ]
 [-0.38405435]
 [ 1.13376944]
 [-1.09989127]
 [-0.17242821]
 [-0.87785842]
 [ 0.04221375]
 [ 0.58281521]
 [-1.10061918]
 [ 1.14472371]
 [ 0.90159072]
 [ 0.50249434]
 [ 0.90085595]
 [-0.68372786]
 [-0.12289023]
 [-0.93576943]
 [-0.26788808]
 [ 0.53035547]
 [-0.69166075]
 [-0.39675353]
 [-0.6871727 ]
 [-0.84520564]
 [-0.67124613]
 [-0.0126646 ]
 [-1.11731035]
 [ 0.2344157 ]
 [ 1.65980218]
 [ 0.74204416]
 [-0.19183555]
 [-0.88762896]
 [-0.74715829]
 [ 1.6924546 ]
 [ 0.05080775]
 [-0.63699565]
 [ 0.19091548]
 [ 2.10025514]
 [ 0.12015895]
 [ 0.61720311]
 [ 0.30017032]
 [-0.35224985]
 [-1.1425182 ]
 [-0.34934272]
 [-0.20889423]
 [ 0.58662319]
 [ 0.83898341]
 [ 0.93110208]
 [ 0.28558733]
 [ 0.88514116]
 [-0.75439794]
 [ 1.25286816]
 [ 0.51292982]
 [-0.29809284]
 [ 0.48851815]
 [-0.07557171]
 [ 1.13162

Horizontal Stacking: Stack Rowwise (similar to np.concatenate, with axis=1).

In [69]:
H_Stack = np.hstack((rand_1, rand_2, rand_3))
print(H_Stack)

[[ 1.62434536  0.30017032 -0.44712856]
 [-0.61175641 -0.35224985  1.2245077 ]
 [-0.52817175 -1.1425182   0.40349164]
 [-1.07296862 -0.34934272  0.59357852]
 [ 0.86540763 -0.20889423 -1.09491185]
 [-2.3015387   0.58662319  0.16938243]
 [ 1.74481176  0.83898341  0.74055645]
 [-0.7612069   0.93110208 -0.9537006 ]
 [ 0.3190391   0.28558733 -0.26621851]
 [-0.24937038  0.88514116  0.03261455]
 [ 1.46210794 -0.75439794 -1.37311732]
 [-2.06014071  1.25286816  0.31515939]
 [-0.3224172   0.51292982  0.84616065]
 [-0.38405435 -0.29809284 -0.85951594]
 [ 1.13376944  0.48851815  0.35054598]
 [-1.09989127 -0.07557171 -1.31228341]
 [-0.17242821  1.13162939 -0.03869551]
 [-0.87785842  1.51981682 -1.61577235]
 [ 0.04221375  2.18557541  1.12141771]
 [ 0.58281521 -1.39649634  0.40890054]
 [-1.10061918 -1.44411381 -0.02461696]
 [ 1.14472371 -0.50446586 -0.77516162]
 [ 0.90159072  0.16003707  1.27375593]
 [ 0.50249434  0.87616892  1.96710175]
 [ 0.90085595  0.31563495 -1.85798186]
 [-0.68372786 -2.02220122

### Reshaping

Reshape V_Stack to a 50 x 3 matrix (after 50 rows, values are placed in a new column). 

In [70]:
V_Stack_Reshape = V_Stack.reshape(50, 3)
print(V_Stack_Reshape)

[[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]
 [ 1.74481176 -0.7612069   0.3190391 ]
 [-0.24937038  1.46210794 -2.06014071]
 [-0.3224172  -0.38405435  1.13376944]
 [-1.09989127 -0.17242821 -0.87785842]
 [ 0.04221375  0.58281521 -1.10061918]
 [ 1.14472371  0.90159072  0.50249434]
 [ 0.90085595 -0.68372786 -0.12289023]
 [-0.93576943 -0.26788808  0.53035547]
 [-0.69166075 -0.39675353 -0.6871727 ]
 [-0.84520564 -0.67124613 -0.0126646 ]
 [-1.11731035  0.2344157   1.65980218]
 [ 0.74204416 -0.19183555 -0.88762896]
 [-0.74715829  1.6924546   0.05080775]
 [-0.63699565  0.19091548  2.10025514]
 [ 0.12015895  0.61720311  0.30017032]
 [-0.35224985 -1.1425182  -0.34934272]
 [-0.20889423  0.58662319  0.83898341]
 [ 0.93110208  0.28558733  0.88514116]
 [-0.75439794  1.25286816  0.51292982]
 [-0.29809284  0.48851815 -0.07557171]
 [ 1.13162939  1.51981682  2.18557541]
 [-1.39649634 -1.44411381 -0.50446586]
 [ 0.16003707  0.87616892  0.31563495]
 [-2.02220122 -0.30620401

Reshape H_Stack to a 150 x 1 matrix (within 1 column, values are placed in a new row). 

In [71]:
H_Stack_Reshape = H_Stack.reshape(150, 1) 
print(H_Stack_Reshape)

[[ 1.62434536]
 [ 0.30017032]
 [-0.44712856]
 [-0.61175641]
 [-0.35224985]
 [ 1.2245077 ]
 [-0.52817175]
 [-1.1425182 ]
 [ 0.40349164]
 [-1.07296862]
 [-0.34934272]
 [ 0.59357852]
 [ 0.86540763]
 [-0.20889423]
 [-1.09491185]
 [-2.3015387 ]
 [ 0.58662319]
 [ 0.16938243]
 [ 1.74481176]
 [ 0.83898341]
 [ 0.74055645]
 [-0.7612069 ]
 [ 0.93110208]
 [-0.9537006 ]
 [ 0.3190391 ]
 [ 0.28558733]
 [-0.26621851]
 [-0.24937038]
 [ 0.88514116]
 [ 0.03261455]
 [ 1.46210794]
 [-0.75439794]
 [-1.37311732]
 [-2.06014071]
 [ 1.25286816]
 [ 0.31515939]
 [-0.3224172 ]
 [ 0.51292982]
 [ 0.84616065]
 [-0.38405435]
 [-0.29809284]
 [-0.85951594]
 [ 1.13376944]
 [ 0.48851815]
 [ 0.35054598]
 [-1.09989127]
 [-0.07557171]
 [-1.31228341]
 [-0.17242821]
 [ 1.13162939]
 [-0.03869551]
 [-0.87785842]
 [ 1.51981682]
 [-1.61577235]
 [ 0.04221375]
 [ 2.18557541]
 [ 1.12141771]
 [ 0.58281521]
 [-1.39649634]
 [ 0.40890054]
 [-1.10061918]
 [-1.44411381]
 [-0.02461696]
 [ 1.14472371]
 [-0.50446586]
 [-0.77516162]
 [ 0.90159

#Reshaping V_Stack (H_Stack) does not give the same output as H_Stack (V_Stack), even though both have similar dimensions. 

### Splitting

Split Rowwise: Each row is converted to an array.

In [72]:
V_Split = np.vsplit(V_Stack, 50)
print(V_Split)

[array([[ 1.62434536],
       [-0.61175641],
       [-0.52817175]]), array([[-1.07296862],
       [ 0.86540763],
       [-2.3015387 ]]), array([[ 1.74481176],
       [-0.7612069 ],
       [ 0.3190391 ]]), array([[-0.24937038],
       [ 1.46210794],
       [-2.06014071]]), array([[-0.3224172 ],
       [-0.38405435],
       [ 1.13376944]]), array([[-1.09989127],
       [-0.17242821],
       [-0.87785842]]), array([[ 0.04221375],
       [ 0.58281521],
       [-1.10061918]]), array([[1.14472371],
       [0.90159072],
       [0.50249434]]), array([[ 0.90085595],
       [-0.68372786],
       [-0.12289023]]), array([[-0.93576943],
       [-0.26788808],
       [ 0.53035547]]), array([[-0.69166075],
       [-0.39675353],
       [-0.6871727 ]]), array([[-0.84520564],
       [-0.67124613],
       [-0.0126646 ]]), array([[-1.11731035],
       [ 0.2344157 ],
       [ 1.65980218]]), array([[ 0.74204416],
       [-0.19183555],
       [-0.88762896]]), array([[-0.74715829],
       [ 1.6924546 ],
      

Split Columnwise: Each column is converted to an array. 

In [73]:
H_Split = np.hsplit(H_Stack, 3)
print(H_Split)

[array([[ 1.62434536],
       [-0.61175641],
       [-0.52817175],
       [-1.07296862],
       [ 0.86540763],
       [-2.3015387 ],
       [ 1.74481176],
       [-0.7612069 ],
       [ 0.3190391 ],
       [-0.24937038],
       [ 1.46210794],
       [-2.06014071],
       [-0.3224172 ],
       [-0.38405435],
       [ 1.13376944],
       [-1.09989127],
       [-0.17242821],
       [-0.87785842],
       [ 0.04221375],
       [ 0.58281521],
       [-1.10061918],
       [ 1.14472371],
       [ 0.90159072],
       [ 0.50249434],
       [ 0.90085595],
       [-0.68372786],
       [-0.12289023],
       [-0.93576943],
       [-0.26788808],
       [ 0.53035547],
       [-0.69166075],
       [-0.39675353],
       [-0.6871727 ],
       [-0.84520564],
       [-0.67124613],
       [-0.0126646 ],
       [-1.11731035],
       [ 0.2344157 ],
       [ 1.65980218],
       [ 0.74204416],
       [-0.19183555],
       [-0.88762896],
       [-0.74715829],
       [ 1.6924546 ],
       [ 0.05080775],
       [-

## Operations

Creating a 50 x 10 matrix of random numbers.

In [74]:
np.random.seed(1)
rand  = np.random.normal(0,1, size = (50, 10))

### np.repeat() - Create a new matrix by repeating each row/column.

Repeat each row: Repeated rows are saved after the original.

In [75]:
repeat_rand_row = np.repeat(rand, 2, axis = 0)
print(repeat_rand_row)

[[ 1.62434536e+00 -6.11756414e-01 -5.28171752e-01 -1.07296862e+00
   8.65407629e-01 -2.30153870e+00  1.74481176e+00 -7.61206901e-01
   3.19039096e-01 -2.49370375e-01]
 [ 1.62434536e+00 -6.11756414e-01 -5.28171752e-01 -1.07296862e+00
   8.65407629e-01 -2.30153870e+00  1.74481176e+00 -7.61206901e-01
   3.19039096e-01 -2.49370375e-01]
 [ 1.46210794e+00 -2.06014071e+00 -3.22417204e-01 -3.84054355e-01
   1.13376944e+00 -1.09989127e+00 -1.72428208e-01 -8.77858418e-01
   4.22137467e-02  5.82815214e-01]
 [ 1.46210794e+00 -2.06014071e+00 -3.22417204e-01 -3.84054355e-01
   1.13376944e+00 -1.09989127e+00 -1.72428208e-01 -8.77858418e-01
   4.22137467e-02  5.82815214e-01]
 [-1.10061918e+00  1.14472371e+00  9.01590721e-01  5.02494339e-01
   9.00855949e-01 -6.83727859e-01 -1.22890226e-01 -9.35769434e-01
  -2.67888080e-01  5.30355467e-01]
 [-1.10061918e+00  1.14472371e+00  9.01590721e-01  5.02494339e-01
   9.00855949e-01 -6.83727859e-01 -1.22890226e-01 -9.35769434e-01
  -2.67888080e-01  5.30355467e-01

Repeat each column: Repeated columns are saved after the original.

In [76]:
repeat_rand_column = np.repeat(rand, 2, axis = 1)
print(repeat_rand_column)

[[ 1.62434536e+00  1.62434536e+00 -6.11756414e-01 -6.11756414e-01
  -5.28171752e-01 -5.28171752e-01 -1.07296862e+00 -1.07296862e+00
   8.65407629e-01  8.65407629e-01 -2.30153870e+00 -2.30153870e+00
   1.74481176e+00  1.74481176e+00 -7.61206901e-01 -7.61206901e-01
   3.19039096e-01  3.19039096e-01 -2.49370375e-01 -2.49370375e-01]
 [ 1.46210794e+00  1.46210794e+00 -2.06014071e+00 -2.06014071e+00
  -3.22417204e-01 -3.22417204e-01 -3.84054355e-01 -3.84054355e-01
   1.13376944e+00  1.13376944e+00 -1.09989127e+00 -1.09989127e+00
  -1.72428208e-01 -1.72428208e-01 -8.77858418e-01 -8.77858418e-01
   4.22137467e-02  4.22137467e-02  5.82815214e-01  5.82815214e-01]
 [-1.10061918e+00 -1.10061918e+00  1.14472371e+00  1.14472371e+00
   9.01590721e-01  9.01590721e-01  5.02494339e-01  5.02494339e-01
   9.00855949e-01  9.00855949e-01 -6.83727859e-01 -6.83727859e-01
  -1.22890226e-01 -1.22890226e-01 -9.35769434e-01 -9.35769434e-01
  -2.67888080e-01 -2.67888080e-01  5.30355467e-01  5.30355467e-01]
 [-6.91

### np.insert() - insert rows and columns within a matrix

Inserting a row of 5s after the first row.  

In [77]:
rand_insert_row = np.insert(rand, 1, 5, axis = 0)
print(rand_insert_row)

[[ 1.62434536e+00 -6.11756414e-01 -5.28171752e-01 -1.07296862e+00
   8.65407629e-01 -2.30153870e+00  1.74481176e+00 -7.61206901e-01
   3.19039096e-01 -2.49370375e-01]
 [ 5.00000000e+00  5.00000000e+00  5.00000000e+00  5.00000000e+00
   5.00000000e+00  5.00000000e+00  5.00000000e+00  5.00000000e+00
   5.00000000e+00  5.00000000e+00]
 [ 1.46210794e+00 -2.06014071e+00 -3.22417204e-01 -3.84054355e-01
   1.13376944e+00 -1.09989127e+00 -1.72428208e-01 -8.77858418e-01
   4.22137467e-02  5.82815214e-01]
 [-1.10061918e+00  1.14472371e+00  9.01590721e-01  5.02494339e-01
   9.00855949e-01 -6.83727859e-01 -1.22890226e-01 -9.35769434e-01
  -2.67888080e-01  5.30355467e-01]
 [-6.91660752e-01 -3.96753527e-01 -6.87172700e-01 -8.45205641e-01
  -6.71246131e-01 -1.26645989e-02 -1.11731035e+00  2.34415698e-01
   1.65980218e+00  7.42044161e-01]
 [-1.91835552e-01 -8.87628964e-01 -7.47158294e-01  1.69245460e+00
   5.08077548e-02 -6.36995647e-01  1.90915485e-01  2.10025514e+00
   1.20158952e-01  6.17203110e-01

Inserting a column of 5s after the first column.

In [78]:
rand_insert_column = np.insert(rand, 1, 5, axis = 1)
print(rand_insert_column)

[[ 1.62434536e+00  5.00000000e+00 -6.11756414e-01 -5.28171752e-01
  -1.07296862e+00  8.65407629e-01 -2.30153870e+00  1.74481176e+00
  -7.61206901e-01  3.19039096e-01 -2.49370375e-01]
 [ 1.46210794e+00  5.00000000e+00 -2.06014071e+00 -3.22417204e-01
  -3.84054355e-01  1.13376944e+00 -1.09989127e+00 -1.72428208e-01
  -8.77858418e-01  4.22137467e-02  5.82815214e-01]
 [-1.10061918e+00  5.00000000e+00  1.14472371e+00  9.01590721e-01
   5.02494339e-01  9.00855949e-01 -6.83727859e-01 -1.22890226e-01
  -9.35769434e-01 -2.67888080e-01  5.30355467e-01]
 [-6.91660752e-01  5.00000000e+00 -3.96753527e-01 -6.87172700e-01
  -8.45205641e-01 -6.71246131e-01 -1.26645989e-02 -1.11731035e+00
   2.34415698e-01  1.65980218e+00  7.42044161e-01]
 [-1.91835552e-01  5.00000000e+00 -8.87628964e-01 -7.47158294e-01
   1.69245460e+00  5.08077548e-02 -6.36995647e-01  1.90915485e-01
   2.10025514e+00  1.20158952e-01  6.17203110e-01]
 [ 3.00170320e-01  5.00000000e+00 -3.52249846e-01 -1.14251820e+00
  -3.49342722e-01 -

### Replace and Overwritting

Overwrite row values in the first row, with new values generated.

In [79]:
New_Values_Row = np.random.normal(0,1, size=(1,10))*50 #pay close attention to the indices (1 x 10  matrix for row).
rand[0] = New_Values_Row
print(rand)

[[-8.59697237e+01  2.85604980e+00 -3.99773745e+01 -1.45797298e+01
  -1.29491427e+01  9.46465988e+00 -2.81894367e+01  4.48432037e+00
  -3.00578400e+01  2.78036755e+01]
 [ 1.46210794e+00 -2.06014071e+00 -3.22417204e-01 -3.84054355e-01
   1.13376944e+00 -1.09989127e+00 -1.72428208e-01 -8.77858418e-01
   4.22137467e-02  5.82815214e-01]
 [-1.10061918e+00  1.14472371e+00  9.01590721e-01  5.02494339e-01
   9.00855949e-01 -6.83727859e-01 -1.22890226e-01 -9.35769434e-01
  -2.67888080e-01  5.30355467e-01]
 [-6.91660752e-01 -3.96753527e-01 -6.87172700e-01 -8.45205641e-01
  -6.71246131e-01 -1.26645989e-02 -1.11731035e+00  2.34415698e-01
   1.65980218e+00  7.42044161e-01]
 [-1.91835552e-01 -8.87628964e-01 -7.47158294e-01  1.69245460e+00
   5.08077548e-02 -6.36995647e-01  1.90915485e-01  2.10025514e+00
   1.20158952e-01  6.17203110e-01]
 [ 3.00170320e-01 -3.52249846e-01 -1.14251820e+00 -3.49342722e-01
  -2.08894233e-01  5.86623191e-01  8.38983414e-01  9.31102081e-01
   2.85587325e-01  8.85141164e-01

Overwrite column values in the first row, with new values generated.

In [80]:
New_Values_Column = np.random.normal(0, 1, size = 50) * 50 #pay close attention to the indices (50 x 1 matrix for column).
rand[:,0] = New_Values_Column
print(rand)

[[ 8.46904557e+01  2.85604980e+00 -3.99773745e+01 -1.45797298e+01
  -1.29491427e+01  9.46465988e+00 -2.81894367e+01  4.48432037e+00
  -3.00578400e+01  2.78036755e+01]
 [ 9.84348896e+00 -2.06014071e+00 -3.22417204e-01 -3.84054355e-01
   1.13376944e+00 -1.09989127e+00 -1.72428208e-01 -8.77858418e-01
   4.22137467e-02  5.82815214e-01]
 [ 8.49346277e+00  1.14472371e+00  9.01590721e-01  5.02494339e-01
   9.00855949e-01 -6.83727859e-01 -1.22890226e-01 -9.35769434e-01
  -2.67888080e-01  5.30355467e-01]
 [-5.82003986e+01 -3.96753527e-01 -6.87172700e-01 -8.45205641e-01
  -6.71246131e-01 -1.26645989e-02 -1.11731035e+00  2.34415698e-01
   1.65980218e+00  7.42044161e-01]
 [ 3.46683113e+01 -8.87628964e-01 -7.47158294e-01  1.69245460e+00
   5.08077548e-02 -6.36995647e-01  1.90915485e-01  2.10025514e+00
   1.20158952e-01  6.17203110e-01]
 [-3.79033664e+01 -3.52249846e-01 -1.14251820e+00 -3.49342722e-01
  -2.08894233e-01  5.86623191e-01  8.38983414e-01  9.31102081e-01
   2.85587325e-01  8.85141164e-01

### Zero-padding

In [81]:
np.random.seed(1) 
rand = np.random.normal(0,1, size = (50, 10))

(1, 1): Pad-width: define how many rows and columns from the edge must be padded. 

In [82]:
Zero_Pad = np.pad(rand, (1, 1), 'constant', constant_values = 0) 
print(Zero_Pad)

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.62434536e+00 -6.11756414e-01 -5.28171752e-01
  -1.07296862e+00  8.65407629e-01 -2.30153870e+00  1.74481176e+00
  -7.61206901e-01  3.19039096e-01 -2.49370375e-01  0.00000000e+00]
 [ 0.00000000e+00  1.46210794e+00 -2.06014071e+00 -3.22417204e-01
  -3.84054355e-01  1.13376944e+00 -1.09989127e+00 -1.72428208e-01
  -8.77858418e-01  4.22137467e-02  5.82815214e-01  0.00000000e+00]
 [ 0.00000000e+00 -1.10061918e+00  1.14472371e+00  9.01590721e-01
   5.02494339e-01  9.00855949e-01 -6.83727859e-01 -1.22890226e-01
  -9.35769434e-01 -2.67888080e-01  5.30355467e-01  0.00000000e+00]
 [ 0.00000000e+00 -6.91660752e-01 -3.96753527e-01 -6.87172700e-01
  -8.45205641e-01 -6.71246131e-01 -1.26645989e-02 -1.11731035e+00
   2.34415698e-01  1.65980218e+00  7.42044161e-01  0.00000000e+00]
 [ 0.

Mean Padding: Padding (1,1) with the mean values from each row and column.

In [83]:
Mean_Pad = np.pad(rand, (1, 1), 'mean') 
print(Mean_Pad)

[[ 5.34368943e-02 -4.41781068e-03  2.54340918e-02  1.26746347e-01
   2.93496714e-01  8.61618587e-02 -1.56908748e-01  1.66800288e-02
   2.38514185e-03  7.41336499e-02  7.06576698e-02  5.34368943e-02]
 [-9.71408908e-02  1.62434536e+00 -6.11756414e-01 -5.28171752e-01
  -1.07296862e+00  8.65407629e-01 -2.30153870e+00  1.74481176e+00
  -7.61206901e-01  3.19039096e-01 -2.49370375e-01 -9.71408908e-02]
 [-1.69588382e-01  1.46210794e+00 -2.06014071e+00 -3.22417204e-01
  -3.84054355e-01  1.13376944e+00 -1.09989127e+00 -1.72428208e-01
  -8.77858418e-01  4.22137467e-02  5.82815214e-01 -1.69588382e-01]
 [ 8.69125410e-02 -1.10061918e+00  1.14472371e+00  9.01590721e-01
   5.02494339e-01  9.00855949e-01 -6.83727859e-01 -1.22890226e-01
  -9.35769434e-01 -2.67888080e-01  5.30355467e-01  8.69125410e-02]
 [-1.78575166e-01 -6.91660752e-01 -3.96753527e-01 -6.87172700e-01
  -8.45205641e-01 -6.71246131e-01 -1.26645989e-02 -1.11731035e+00
   2.34415698e-01  1.65980218e+00  7.42044161e-01 -1.78575166e-01]
 [ 2.

### np.delete() - Deleting Rows and Columns from a Matrix.

Delete a Row

In [84]:
Rand_del_row = np.delete(rand, 1, axis = 0)
print(Rand_del_row)

[[ 1.62434536e+00 -6.11756414e-01 -5.28171752e-01 -1.07296862e+00
   8.65407629e-01 -2.30153870e+00  1.74481176e+00 -7.61206901e-01
   3.19039096e-01 -2.49370375e-01]
 [-1.10061918e+00  1.14472371e+00  9.01590721e-01  5.02494339e-01
   9.00855949e-01 -6.83727859e-01 -1.22890226e-01 -9.35769434e-01
  -2.67888080e-01  5.30355467e-01]
 [-6.91660752e-01 -3.96753527e-01 -6.87172700e-01 -8.45205641e-01
  -6.71246131e-01 -1.26645989e-02 -1.11731035e+00  2.34415698e-01
   1.65980218e+00  7.42044161e-01]
 [-1.91835552e-01 -8.87628964e-01 -7.47158294e-01  1.69245460e+00
   5.08077548e-02 -6.36995647e-01  1.90915485e-01  2.10025514e+00
   1.20158952e-01  6.17203110e-01]
 [ 3.00170320e-01 -3.52249846e-01 -1.14251820e+00 -3.49342722e-01
  -2.08894233e-01  5.86623191e-01  8.38983414e-01  9.31102081e-01
   2.85587325e-01  8.85141164e-01]
 [-7.54397941e-01  1.25286816e+00  5.12929820e-01 -2.98092835e-01
   4.88518147e-01 -7.55717130e-02  1.13162939e+00  1.51981682e+00
   2.18557541e+00 -1.39649634e+00

Delete a Column

In [85]:
Rand_del_column = np.delete(rand, 1, axis = 1)
print(Rand_del_column)

[[ 1.62434536e+00 -5.28171752e-01 -1.07296862e+00  8.65407629e-01
  -2.30153870e+00  1.74481176e+00 -7.61206901e-01  3.19039096e-01
  -2.49370375e-01]
 [ 1.46210794e+00 -3.22417204e-01 -3.84054355e-01  1.13376944e+00
  -1.09989127e+00 -1.72428208e-01 -8.77858418e-01  4.22137467e-02
   5.82815214e-01]
 [-1.10061918e+00  9.01590721e-01  5.02494339e-01  9.00855949e-01
  -6.83727859e-01 -1.22890226e-01 -9.35769434e-01 -2.67888080e-01
   5.30355467e-01]
 [-6.91660752e-01 -6.87172700e-01 -8.45205641e-01 -6.71246131e-01
  -1.26645989e-02 -1.11731035e+00  2.34415698e-01  1.65980218e+00
   7.42044161e-01]
 [-1.91835552e-01 -7.47158294e-01  1.69245460e+00  5.08077548e-02
  -6.36995647e-01  1.90915485e-01  2.10025514e+00  1.20158952e-01
   6.17203110e-01]
 [ 3.00170320e-01 -1.14251820e+00 -3.49342722e-01 -2.08894233e-01
   5.86623191e-01  8.38983414e-01  9.31102081e-01  2.85587325e-01
   8.85141164e-01]
 [-7.54397941e-01  5.12929820e-01 -2.98092835e-01  4.88518147e-01
  -7.55717130e-02  1.1316293