# Session 2: Introduction to NumPy 

NumPy is a Numerical Computing Python Library used for conducting mathematical operations of large, multidimensional arrays. 

    - Arrays and Operations are vectorised: No explicit Looping or Indexing is required, making it readable and similar to standard mathematical notation. 

    - Arrays can be created in any dimensioms: Allows for mathematical, and statistical operations, that are frequently used in scientific computing. 

    - Operations are performed much faster and more efficiently using NumPy: Less Memory and Storage space is occupied. 

NumPy is designed to work seamlessly with other scientific computing libraries in Python,  allowing for a wider range of advanced computations and data visualisation.

Applications of NumPy: Data Analysis and Manipulation, Scientific Computing and Simulations, Machine Learning and AI, etc.

For more information: https://numpy.org/doc/stable/user/index.html	




In [44]:

#pip install numpy
import numpy as np


## Basic Array Operations

Array is a contrainer that stores more than one item.

    - Very similar to Lists, however, arrays behave very differently when part of NumPy. 


Vectorised Operations are supported by NumPy arrays, but NOT by Lists. 

    - NumPy arrays makes calculations highly efficient.


Arrays are not mutuable, and can only comprise of ONE type of element.

Suggestion: Use lists for mutable operations, convert them to NumPy arrays for calculations. 


### Creating Arrays


#### Step I: Create a List
In the example below, two lists (A and B) are created.

In [45]:
A = [4, 5, 6]
B = [1, 2, 3]
print(f'A = {A}\nB = {B}')

A = [4, 5, 6]
B = [1, 2, 3]


Lists do not support vectorised operations, placing the '+' operator would join them, rather than conducting an additive operation.

In [46]:
C = A + B
print (f'C = {C}')

C = [4, 5, 6, 1, 2, 3]


#### Step 2: Call the 'array' function from Numpy using np.array()

Convert both Lists into Arrays

In [47]:
Array_A = np.array(A)  #call 'array' function from numpy 
Array_B = np.array(B)

print(f'Array_A = {Array_A}\nArray_B = {Array_B}')

Array_A = [4 5 6]
Array_B = [1 2 3]


#### Step 3: Conduct Operation of Choice

Operation: Addition 

In [48]:
Add = Array_A + Array_B

print(f'Add = {Add}')

Add = [5 7 9]


Operation: Subtraction

In [49]:
Subtract = Array_A - Array_B 
print(f'Subtract = {Subtract}')

Subtract = [3 3 3]


Operation: Multiplication

In [50]:
Multiply = Array_A * Array_B
print(f'Multiply = {Multiply}')

Multiply = [ 4 10 18]


Operation: Division

In [51]:
Divide = Array_A / Array_B
print(f'Divide = {Divide}')

Divide = [4.  2.5 2. ]


Operation: Floor Division

In [52]:
Floor_Div = Array_A//Array_B
print(f'Floor_Div = {Floor_Div}')

Floor_Div = [4 2 2]


Operation: Modulo

In [53]:
Modulo = Array_A % Array_B
print(f'Modulo = {Modulo}')

Modulo = [0 1 0]


Operation: Power

In [54]:
Power = Array_A ** Array_B
print(f'Power = {Power}')

Power = [  4  25 216]


## Indexing and Slicing Arrays

Create an Array using the arange function: Similar to  np.array(range(n)), for n being an integer.

In [55]:
Array = np.arange(0,100)
print(f'Array = {Array}')

Array = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


Elements corresponding with index 1 to 10.

In [56]:
Array[1:10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Elements corresponding with index 1 to 50, at increments of 10.

In [57]:
Array[1:50:10]

array([ 1, 11, 21, 31, 41])

Addition (or any basic operation) with Slicing: Make sure both arrays have the same dimensions (check using .shape).

In [58]:
Array_1 = Array[1:40]
Array_2 = Array[41:80]

Shape_1 = Array_1.shape
Shape_2 = Array_2.shape

print(f' Array_1 = {Array_1}, Shape = {Shape_1}\n\n Array_2  = {Array_2}, Shape = {Shape_2}')

 Array_1 = [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39], Shape = (39,)

 Array_2  = [41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64
 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79], Shape = (39,)


In [59]:
Array_sum = Array_1 + Array_2
Array_sum_shape = Array_sum.shape

print(f' Array_sum = {Array_sum}, Shape = {Array_sum_shape}')

 Array_sum = [ 42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76
  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106 108 110 112
 114 116 118], Shape = (39,)


## Creating a Matrix (2D-Array)

#### Step I: Define each row as a List.
The current example aims to create a 3 x 6 Matrix.

In [60]:
row_1 = [2, 4, 5, 4, 3, 2]
row_2 = [4, 6, 7, 8, 7, 3]
row_3 = [8, 3, 2, 1, 4, 7 ]

print(f' row_1 = {row_1}\n row_2 = {row_2}\n row_3 = {row_3}')

 row_1 = [2, 4, 5, 4, 3, 2]
 row_2 = [4, 6, 7, 8, 7, 3]
 row_3 = [8, 3, 2, 1, 4, 7]


#### Step 2: Create an Array

In [61]:
Matrix_1 = np.array([row_1, row_2, row_3])
Matrix_1_Shape = Matrix_1.shape

print(f' Matrix_1 = {Matrix_1}, Shape = {Matrix_1_Shape}')

 Matrix_1 = [[2 4 5 4 3 2]
 [4 6 7 8 7 3]
 [8 3 2 1 4 7]], Shape = (3, 6)


## Basic Matrix Operations

Create another 3 x 6 matrix

In [62]:
Matrix_2 = np.array([[1, 2, 4, 2, 5, 8], [3, 5, 7, 6, 9, 8], [4, 6, 7, 7, 8,7]])
Matrix_2_Shape = Matrix_2.shape 


print(f' Matrix_2 = {Matrix_2}, Shape = {Matrix_2_Shape}')

 Matrix_2 = [[1 2 4 2 5 8]
 [3 5 7 6 9 8]
 [4 6 7 7 8 7]], Shape = (3, 6)


Operation: Addition

In [63]:
Add_Matrix = Matrix_1 + Matrix_2
print(f' Add_Matrix = {Add_Matrix}')

 Add_Matrix = [[ 3  6  9  6  8 10]
 [ 7 11 14 14 16 11]
 [12  9  9  8 12 14]]


Operation: Subtraction

In [64]:
Subtract_Matrix = Matrix_1 - Matrix_2
print(f' Subtract_Matrix = {Subtract_Matrix}')

 Subtract_Matrix = [[ 1  2  1  2 -2 -6]
 [ 1  1  0  2 -2 -5]
 [ 4 -3 -5 -6 -4  0]]


Operation: Multiplication (Element by Element)

In [65]:
Multiplication_Matrix = Matrix_1 * Matrix_2 
print(f' Multiplication_Matrix = {Multiplication_Matrix}')

 Multiplication_Matrix = [[ 2  8 20  8 15 16]
 [12 30 49 48 63 24]
 [32 18 14  7 32 49]]


Operation: Division (Elemnet by Element)

In [66]:
Division_Matrix = Matrix_1/Matrix_2
print(f' Division_Matrix = {Division_Matrix}')

 Division_Matrix = [[2.         2.         1.25       2.         0.6        0.25      ]
 [1.33333333 1.2        1.         1.33333333 0.77777778 0.375     ]
 [2.         0.5        0.28571429 0.14285714 0.5        1.        ]]


Operation: Matrix Multiplication 
Ensure the dimensions of the matrices are valid for multiplication.

Step I: Transpose Matrix_2 to Matrix_2T

Step II: Matrix_1 (3 x 6) x Matrix_2T (6 x 3)

In [67]:
Matrix_2T = np.transpose(Matrix_2)
Mat_Mul = np.matmul(Matrix_1, Matrix_2T)

print(f'Matrix_2_Transpose = {Matrix_2T}\n\nMat_Mul = {Mat_Mul}')

Matrix_2_Transpose = [[1 3 4]
 [2 5 6]
 [4 7 7]
 [2 6 7]
 [5 9 8]
 [8 8 7]]

Mat_Mul = [[ 69 128 133]
 [119 226 234]
 [100 151 152]]


## Slicing and Indexing Matrices

All elements in the first row (index = 0) of Matrix_1

In [68]:
Matrix_1[0]

array([2, 4, 5, 4, 3, 2])

All elements in all the row, corresponding to the first column (index = 0)

In [69]:
Matrix_1[:,0]

array([2, 4, 8])

Element corresponding to row index 1, and column index 2

In [70]:
Matrix_1[1, 2]

7

Element indexed at 2, within row indexed at 1

In [71]:
Matrix_1[1][2]

7

Element within rows at index 0 to 2 (excluding 2), and columns 4 to 6 (excluding 6)

In [72]:
Matrix_1[0:2, 4:6]

array([[3, 2],
       [7, 3]])

From Matrix_1, includes only variables that are greater than 4

In [73]:
Matrix_1[Matrix_1>4]

array([5, 6, 7, 8, 7, 8, 7])

From Matrix_1, includes only variables that are greater than 3, and less than equal to 6

In [74]:
Matrix_1[(Matrix_1 > 3) & (Matrix_1 <= 6)] 

array([4, 5, 4, 4, 6, 4])

## Linear Algebra

#### np.linalg(): Designed to allow efficient implementation of basic linear algebra algorithms.

Create two (3 x 3) Matrices: Matrix_A and Matrix_B

In [75]:
Matrix_1 = np.array([[2, 4, 5], [4, 6, 7], [8, 3, 2]]) 
Matrix_2 = np.array([[1, 2, 4], [3, 5, 7], [4, 6, 7]]) 

Operation: Transpose

In [76]:
Matrix_1T = np.transpose(Matrix_1)
print(f' Matrix_1T = {Matrix_1T}')

 Matrix_1T = [[2 4 8]
 [4 6 3]
 [5 7 2]]


Operation: Eigen Value

In [77]:
Eigen_Value = np.linalg.eigvals(Matrix_1)
print(f' Eigen_Value = {Eigen_Value}')

 Eigen_Value = [13.57659974 -3.69616603  0.11956629]


Operation: Rank

In [78]:
Rank = np.linalg.matrix_rank(Matrix_1) 
print(f' Rank  = {Rank}')

 Rank  = 3


Operation: Trace (sum of diagonal)

In [79]:
Trace = np.trace(Matrix_1)
print(f' Trace = {Trace}')

 Trace = 10


Operation: Determinant

In [80]:
Det = np.linalg.det(Matrix_1)
print(f' Det = {Det}')

 Det = -6.000000000000011


Operation: Inverse

In [81]:
Inv = np.linalg.inv(Matrix_1)
print (f' Inv = {Inv}')

 Inv = [[ 1.5        -1.16666667  0.33333333]
 [-8.          6.         -1.        ]
 [ 6.         -4.33333333  0.66666667]]


Operation: Identity Matrix (Checking Inverse Output)

In [82]:
Iden_Matrix_1 = np.matmul(Matrix_1, Inv)
print(f' Iden_Matrix_1 = {Iden_Matrix_1}')

 Iden_Matrix_1 = [[ 1.00000000e+00  2.66453526e-15 -2.22044605e-16]
 [-3.55271368e-15  1.00000000e+00 -2.22044605e-16]
 [ 0.00000000e+00 -1.77635684e-15  1.00000000e+00]]


Solve for A * X = B, where A = Matrix_1, B = Matrix_2, hence X = B * Inverse (A) 

In [83]:
Solve = np.linalg.solve(Matrix_1, Matrix_2)
print(f' Solve = {Solve}')

 Solve = [[-0.66666667 -0.83333333  0.16666667]
 [ 6.          8.          3.        ]
 [-4.33333333 -5.66666667 -1.66666667]]


Use Solve to obtain Matrix_2, from previous solution and Matrix_1

In [84]:
Matrix_2_Solve = np.matmul(Matrix_1, Solve)
print(f' Matrix_2_Solve = {Matrix_2_Solve}')

 Matrix_2_Solve = [[1. 2. 4.]
 [3. 5. 7.]
 [4. 6. 7.]]


Operation: Inner Product 

In [85]:
Inner_Product = np.inner(Matrix_1, Matrix_2)
print(f' Inner_Product = {Inner_Product}')

 Inner_Product = [[ 30  61  67]
 [ 44  91 101]
 [ 22  53  64]]


Operation: Outer Product

In [86]:
Outer_Product = np.outer(Matrix_1, Matrix_2)
print(f' Outer_Product = {Outer_Product}')

 Outer_Product = [[ 2  4  8  6 10 14  8 12 14]
 [ 4  8 16 12 20 28 16 24 28]
 [ 5 10 20 15 25 35 20 30 35]
 [ 4  8 16 12 20 28 16 24 28]
 [ 6 12 24 18 30 42 24 36 42]
 [ 7 14 28 21 35 49 28 42 49]
 [ 8 16 32 24 40 56 32 48 56]
 [ 3  6 12  9 15 21 12 18 21]
 [ 2  4  8  6 10 14  8 12 14]]
